### ISSUE TITLE
no connection links

### ISSUE THREAD

**Issue by akebu6** [zeeshanmahar007/zeeshanmahar007#3]
the connection section has no links, this section could either be removed or links to your social accounts or however you want people to get in touch with you added

**Comment by zeeshanmahar007** [comment]
it is already connected with my social media accounts through Links.

**Comment by akebu6** [comment]
they were not visible on my end because of dark mode and they are also dark. try making them visible on both dark and light mode

**Comment by zeeshanmahar007** [comment]
Yes they are in dark color that's why not visible. I will make them visible. Thank you for the suggestion.

**Comment by akebu6** [comment]
no problem
